### ISSUE TITLE
Search by relation field: failed with 500 error

### ISSUE THREAD

**Issue by vmalyk** [pimcore/advanced-object-search#103]
Hi!

**Pre-condition**:
Pimocre 6.7.3
Advanced search 3.1.7 
Elasticsearch 6.x
 
**Steps to reproduce**:
Looks like After adding default fields to index, Conditions by object_ids or object_filter with ID  don't work. For ex.:
![2020-12-14 23_50_08-eplehuset pimcore upgrade convert no __ Pimcore](https://user-images.githubusercontent.com/5318027/102181658-13afe380-3ebc-11eb-9c5e-5d00b403849f.png)

We got 500 error with next trace and error with nested type:
![2020-12-14 23_49_39-eplehuset pimcore upgrade convert no __ Pimcore](https://user-images.githubusercontent.com/5318027/102181691-23c7c300-3ebc-11eb-9a2e-304e923e55a4.png)

Please  review,

**Comment by dvesh3** [comment]
@vmalyk why closed it?

**Comment by vmalyk** [comment]
@dvesh3 , looks like We have some issues with Elasticsearch and after update mapping by advanced-object-search:update-mapping issue is gone.
