### ISSUE TITLE
Bug in Service.php --> Release new version

### ISSUE THREAD

**Issue by ppi-buck** [pimcore/advanced-object-search#12]
Hey,

I just came across this already fixed bug https://github.com/pimcore/advanced-object-search/commit/d23b979b37a9ac71d9ddd37c9c88d2cf8f7dbde6#diff-16a921c287a57770d0ab59c0fb771b5d in the Service.php **doFilter()** function and wanted to report it. 

As it's already fixed, can you please release it as a new version so I can update via composer?

Thanks :-)

PS: Any plans on moving to ElasticSearch 6? Right now it doesn't work with ES6 since it uses different types for e.g. a textfield [string vs. text].

**Comment by fashxp** [comment]
new release done. 

concerning ES6 ... right now we don't have any plans yet, but we definitely would accept PRs for that - ideally would support of both, ES5 and ES6

**Comment by ppi-buck** [comment]
We'll see what we can do :-) Thanks for the quick release

**Comment by fashxp** [comment]
thx very much ;-)
