### ISSUE TITLE
[Bug]: Error Undefined array key "id" in ManyToOneRelation and ManyToManyRelation filter

### ISSUE THREAD

**Issue by NikitchenkoSergey** [pimcore/advanced-object-search#136]
### Expected behavior

Filter by relation works.

### Actual behavior

When search by relation throw error.
![image](https://user-images.githubusercontent.com/7048202/149516077-79df0ae2-69d5-4b97-a1aa-a909a3fed544.png)

### Steps to reproduce

Create filter by relation:
![image](https://user-images.githubusercontent.com/7048202/149516125-7899b506-fa1c-4c22-8481-fe6e418e9caa.png)

Click Results tab

**Comment by wujku** [comment]
+1

**Comment by wujku** [comment]
@NikitchenkoSergey can you create a pull request with your changes?

**Comment by NikitchenkoSergey** [comment]
@wujku , yes, i created it https://github.com/pimcore/advanced-object-search/pull/137

**Comment by NikitchenkoSergey** [comment]
@wujku do you know when fix will be published?

**Comment by wujku** [comment]
@fashxp are you able to review changes from PR and close them?

**Comment by fashxp** [comment]
just merged
