### ISSUE TITLE
[Bug]: Checkbox 'must not' operator reset to 'must' when opening saved search

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/advanced-object-search#138]
### Expected behavior

When re-opening a saved search i would expect that when a checkbox operator is set to 'must not' the filter is still set to 'must not' when re-opening the saved search.

### Actual behavior

When opening a saved search the operator for checkboxes is always shown as 'must'.

### Steps to reproduce

1. Create a new search, add filter for a checkbox and set this to 'must not'
2. Make sure you have results in the result tab
3. Go to tab 'Save and share', add a name and click 'save' bottom right
4. Close the search and reopen the saved search
5. Go back from 'results' tab to 'filter' tab
6. Filter for checkbox is now showing 'must'
7. When returning to 'results' will give a different result now

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/advanced-object-search/commit/8e17635c0c29a2f0ddd430f01f89b1230e1d066f
