### ISSUE TITLE
[Bug]: Save And Share does not work for non Admins

### ISSUE THREAD

**Issue by ErrolMatthiessen** [pimcore/advanced-object-search#154]
### Expected behavior

A non-admin who has access to the Advanced Object Search is able to save his search

### Actual behavior

When a user hits the save button an exception is raised:

Timestamp: Fri May 27 2022 11:32:44 GMT+0200 (Mitteleuropäische Sommerzeit)
Status: 500 | Internal Server Error
URL: /admin/bundle/advanced-object-search/admin/save
Method: post
Message: Warning: Undefined property: stdClass::$share_globally
Trace: 
in /var/www/pimcore/vendor/pimcore/advanced-object-search/src/Controller/AdminController.php:267
#0 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(152): AdvancedObjectSearchBundle\Controller\AdminController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#1 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /var/www/pimcore/public/index.php(37): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}

### Steps to reproduce

1. Create a new user and give him access to Advanced Object Search and Objects
2. Login as that user
3. Search Icon -> Advanced Object Search -> New
4. Switch to Save and Share tab
5. Press the Save button

The problem is that the share_globally checkbox is not shown for non-admins, but it is required for the saving

**Comment by dvesh3** [comment]
Fixed by #155
