### ISSUE TITLE
[Bug]: Grid maintenance don't work

### ISSUE THREAD

**Issue by Maksonis** [pimcore/advanced-object-search#156]
### Expected behavior

Be able to change and save product through AOS grid.

### Actual behavior

When I try to maintain any attribute then it gives me an error:
![image-20220602-064145](https://user-images.githubusercontent.com/17277953/171575556-8d653036-69fa-43ed-a98c-3947f2cca855.png)

Stacktrace:

`URL: /admin/bundle/advanced-object-search/admin/grid-proxy?classId=LP&xaction=update&_dc=1654148635192
Method: POST
Message: The controller for URI "/admin/bundle/advanced-object-search/admin/grid-proxy" is not callable: Controller "PimcoreAdminBundle:Admin/DataObject/DataObject:gridProxy" does neither exist as service nor as class.
Trace: 
in /var/www/pimcore/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88
#0 /var/www/pimcore/vendor/symfony/http-kernel/Controller/TraceableControllerResolver.php(38): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController()
#1 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(135): Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController()
#2 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#3 /var/www/pimcore/vendor/symfony/framework-bundle/Controller/AbstractController.php(156): Symfony\Component\HttpKernel\HttpKernel->handle()
#4 /var/www/pimcore/vendor/pimcore/advanced-object-search/src/Controller/AdminController.php(101): Symfony\Bundle\FrameworkBundle\Controller\AbstractController->forward()
#5 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(152): AdvancedObjectSearchBundle\Controller\AdminController->gridProxyAction()
#6 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#7 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#8 /var/www/pimcore/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#9 {main}`

### Steps to reproduce

1. Open AOS
2. Select class Car and go to Results tab
3. Try to change color (for example)
![image](https://user-images.githubusercontent.com/17277953/171576409-30e2246c-8a8a-416b-a6bc-836b57faa558.png)

**Comment by dvesh3** [comment]
Fixed by https://github.com/pimcore/advanced-object-search/commit/124e07e8cd71a5ae8fa59a98f1157fcedb805ca9
