### ISSUE TITLE
[Feature]: Add ElasticSearch Authentication

### ISSUE THREAD

**Issue by HSergio9** [pimcore/advanced-object-search#166]
### Feature description

Hello there,

it seems, at least based on this bundle documentation's, that we aren't able to specify any auth credentials for ElasticSearch.
In fact, that makes this bundle not suitable for production use.

It would be great if we can use our ES Username & Password to make auth.

**Comment by fashxp** [comment]
already possible, see https://pimcore.com/docs/platform/Advanced_Object_Search/
