### ISSUE TITLE
Prepare for Symfony 6 upgrade

### ISSUE THREAD

**Issue by dvesh3** [pimcore/advanced-object-search#185]
### Feature description

Related to https://github.com/pimcore/pimcore/issues/13242

and reactivate 11.x-dev tests (phpstan)

**Comment by kingjia90** [comment]
I've took a look, beside requiring #176 and https://github.com/pimcore/advanced-object-search/pull/169, the rest works just fine, so probably we would be able to keep the 10.5 support, if we manage to support both elastic search 7 and 8

**Comment by fashxp** [comment]
@kingjia90 please also reactivate 11.x-dev tests (phpstan)
