### ISSUE TITLE
[Improvement]: Remove childs compatibility layer, when dropping pimcore X support

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/advanced-object-search#186]
### Improvement description

Remove childs compatibility layer, when dropping pimcore X support. Please see https://github.com/pimcore/advanced-object-search/pull/183

**Comment by blankse** [comment]
@wisconaut Why did you close this? The layer still exists:
https://github.com/pimcore/advanced-object-search/blob/4e579f513d8955c740e3548037fc471bac9bd42c/src/Resources/public/js/searchConfig/resultExtension.js#L103-L104

**Comment by ghost** [comment]
@blankse https://github.com/pimcore/advanced-object-search/pull/183 - thought it was fixed by this. Sorry, reopening.

**Comment by herbertroth** [comment]
@blankse This bundle is not under active development any more.
