### ISSUE TITLE
[Task]: Check whether icon should be white or coloured in 11.x

### ISSUE THREAD

**Issue by kingjia90** [pimcore/advanced-object-search#187]
### Improvement description

Due this css code 
https://github.com/pimcore/advanced-object-search/blob/eab1375f53907f875712a1d83983fcec429f4db2/src/Resources/public/css/admin.css#L31-L37

The advanced object search icon appears yellow instead of flat white
![image](https://user-images.githubusercontent.com/6014195/200852516-fe5f0765-8e14-4fcd-934b-4b5a4d4495c0.png)

Check if we should add `.pimcore_version_11` or remove this `.pimcore_version_10` and `.pimcore_version_6`

**Comment by fashxp** [comment]
icon should be white

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/advanced-object-search/pull/188
