### ISSUE TITLE
[Task]: Clean up `createSchema`, `getSchemaManager` BC Layer

### ISSUE THREAD

**Issue by kingjia90** [pimcore/advanced-object-search#193]
### Improvement description

In the installer there are usage of deprecated methods 
[getSchemaManager](https://github.com/doctrine/dbal/pull/5458) and  [createSchema](https://github.com/doctrine/dbal/pull/5613) that would not work once we add support to [DBAL v4](https://github.com/pimcore/pimcore/issues/13015) in Pimcore 11.

Requires https://github.com/pimcore/advanced-object-search/pull/190 , and bump minimum DBAL to ^3.5

**Comment by kingjia90** [comment]
10.6 is still supported, so can't use `getSchemaManager` yet, Lowered priority accordingly

![image](https://user-images.githubusercontent.com/6014195/214829634-2ea16e10-e078-491f-8714-b3d002082459.png)

**Comment by phpkbiz** [comment]
Can someone explain to me how to run the installer mentioned in Readme file.
Installation and Configuration
Installer creates all necessary tables.

**Comment by ghost** [comment]
10.6 is still supported, so can't use getSchemaManager yet, so closing.
