### ISSUE TITLE
[Bug][Installer] Does not mark all migrations as executed

### ISSUE THREAD

**Issue by fashxp** [pimcore/advanced-object-search#213]
### Expected behavior

see https://github.com/pimcore/advanced-object-search/blob/5.x/src/Installer.php#L168

vs. `Version20221130130306`

### Actual behavior

installer should mark all migrations as executed

### Steps to reproduce

.

**Comment by phpkbiz** [comment]
Can someone explain to me how to actually run the installer?

Installation and Configuration
Installer creates all necessary tables.

**Comment by dvesh3** [comment]
Hi @phpkbiz please check [file](https://github.com/pimcore/advanced-object-search/pull/236/files#diff-c5c208b37f8c9ea0141aa72f4f9730c0a7dfae4a42f51b0089056e4cf5602a17) for installation instructions.
