### ISSUE TITLE
Horizontal scroll while building queries

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/advanced-object-search#22]
Hi,

When we are building search queries (conditions/groups) it sometimes happens that the screen width is to small. The operator or value fields fall off the window and it's not possible to use a horizontal scroll.

Is it possible to enable the horizontal scrolling?

**Comment by RuudvdvNB** [comment]
ExtJS panels do support scrolling, if i change the width of the selected panel (see screenshot) i am able to scroll horizontal. But i'm not sure how to add this in the corresponding panels.

![image](https://user-images.githubusercontent.com/36728652/41917477-ca16896e-795a-11e8-9b4a-17b9037f1bba.png)

**Comment by fashxp** [comment]
close this due to inactivity. PRs are still welcome.
