### ISSUE TITLE
[Bug]: Loaded wrong grid configurations for another class

### ISSUE THREAD

**Issue by vmalyk** [pimcore/advanced-object-search#223]
### Expected behavior

Get proper grids configurations related with choosed classId  

### Actual behavior

Get wrong grids

### Steps to reproduce

1. Having more classes as 10, or IDs should be started from the same symbols. For ex., classId "2" and "22".
2. Configured grids for each classes 2 and 22.
3. Open saved search for class 2.
4. Open grid and you get grids for class 22 instead 2.

**Comment by vmalyk** [comment]
After small research issue is related with store.findRecord function and used params in   https://github.com/pimcore/advanced-object-search/blob/5.x/src/Resources/public/js/searchConfig/resultPanel.js#L90-L93 -  
found latest record instead equal and fetched wrong  grids by name after that. 

Looks like it's known case in ExtJS with findRecord and [here](https://fiddle.sencha.com/fiddle/1g7e?height=600) you see example  ho to fix by params - in this case it works correct:

` 
        var classRecord = classStore.findRecord("id", this.classId, 0, false, false, true);
`

Ofc, I can create PR for 5.x release, but it's actual for 4.x too, but I didn't see branches for these previous versions less as Pimcore 11 that marked as LTS in main Pimcore repository. Can anybody clarify why it's gone?

**Comment by dvesh3** [comment]
Hi @vmalyk ver 4.x is not maintained anymore since the release of 5.x as we might need to refactor some bug fixes when merging 4.x into 5.x. Could you please provide a PR based on 5.0?

**Comment by dvesh3** [comment]
Fixed by #226
