### ISSUE TITLE
[Bug]: Filter on localized fields - language & operator selection missing

### ISSUE THREAD

**Issue by itx-markus-weidt** [pimcore/advanced-object-search#228]
### Expected behavior

In Pimcore 10 the filter on a localized field looked like this:
![grafik](https://github.com/pimcore/advanced-object-search/assets/46591316/bae25d48-b2ae-48f3-b1f2-5299decc2b11)
![grafik](https://github.com/pimcore/advanced-object-search/assets/46591316/0f7aec15-12aa-41c8-9470-6366bf27aebd)

You could specify the language on that filter.

### Actual behavior

In Pimcore 11 - also in the [Demo](https://demo.pimcore.com/admin/) - localized fields are not shown correctly in dropdown and - if selected - there is no way to specify the language on a localized field for filtering.

![grafik](https://github.com/pimcore/advanced-object-search/assets/46591316/0bda0a92-a900-4c19-9a54-6b6c9f51e3d6)
![grafik](https://github.com/pimcore/advanced-object-search/assets/46591316/a0eb5df0-74b8-4baa-9629-9b9c7d5c0658)

Screenshots are from official demo.

### Steps to reproduce

In [Demo ](https://demo.pimcore.com/admin/)

1. Open Advanced Object Search / New
2. Select Class "News"
3. Add filter "condition"
4. Select "invisible" field between Path and Content

**Comment by kingjia90** [comment]
Resolved by #232
