### ISSUE TITLE
[Documentation] Informe Elasticsearch version compatible

### ISSUE THREAD

**Issue by Yivan** [pimcore/advanced-object-search#23]
ElasticSearch too (v5 and/or v6 ?) version isn't mentionned in the documentation for the Advanced Object Search.

It seems the plugin is compatible >= v5 < 6 of ElasticSearch (according to https://github.com/ongr-io/ElasticsearchDSL#version-matrix).
But i think it should be clearly said on the requirement documentation of the plugin to help developpers.

Thanks.

**Comment by dkarlovi** [comment]
A better thing would be to support new ES versions. :)

**Comment by fashxp** [comment]
PRs are as always welcome ;-)

**Comment by Yivan** [comment]
I come back to this issue. We are updating our stack with the upcoming (6 july) of the new stable debian 10.
We want to use new version of elasticsearch. Pimcore ecommerce seems to supporte elastic v5 or v6, but advanced search only v5. Is it planned to make it work on v6 ?

We wanted to switch directly to v7, but Pimcore ecommerce and advanced search don't seems to support it, so we will stay on v6. But it would be nice to be able to use this extension with v6, to be coherent with Pimcore ecommerce.

Elastic v5 is no more supported so it is no more an option for new projects... and so this extension cannot be use : ((
https://www.elastic.co/fr/support/eol

At least elastic 6 is an important point for this addon.
And i think at some times having elasticsearch 7 for Pimcore would be nice! (but not the priority)

I am not able to provide a PR sorry, but I hope someone knowing this extension could.

Thanks.

**Comment by fashxp** [comment]
currently it is ES5, ES6 support is on the way for next major release, see https://github.com/pimcore/advanced-object-search/pull/59
