### ISSUE TITLE
[Improvement]: Can you tell me how the Installer works exactly, 

### ISSUE THREAD

**Issue by phpkbiz** [pimcore/advanced-object-search#237]
### Improvement description

Can you tell me how the Installer works exactly, or how can we install the advanced-object-search module?

Readme.md guide
==== 
Installation and Configuration
Installer creates all necessary tables.

Also when I install by
composer require pimcore/advanced-object-search

It get installed by name
**PimcoreSimpleBackendSearch**

**Comment by herbertroth** [comment]
We do not provide support for community bundles.
