### ISSUE TITLE
[Improvement]: Please tell how to get access for advancd object search in admin area

### ISSUE THREAD

**Issue by phpkbiz** [pimcore/advanced-object-search#238]
### Improvement description

After installing all modules related to advanced object search and doing configuration for it, The advanced-object-search does not appear in the admin area.

**Comment by dvesh3** [comment]
Hi @phpkbiz please use [Discussions](https://github.com/pimcore/pimcore/discussions) for your queries. This section is used for submitting confirmed issues e.g. bugs, improvements & new feature requests. Thanks for your understanding :pray:
