### ISSUE TITLE
[Bug]: Xlsx export issue with ES8 and Advanced Object Search 5

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/advanced-object-search#256]
### Expected behavior

A file to be downloaded.

### Actual behavior

```
Pimcore\Model\DataObject\Service::getCsvData(): Argument #4 ($fields) must be of type array, null given, 
called in /var/www/pimcore/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectHelperController.php on line 1351
```

Issue can be seen here where `$fields` is `null`.

![Screenshot 2024-02-13 at 14 33 35](https://github.com/pimcore/advanced-object-search/assets/279826/065e19af-8860-49a8-b303-9ab418562ac1)

### Steps to reproduce

![Screenshot 2024-02-13 at 14 34 28](https://github.com/pimcore/advanced-object-search/assets/279826/9fbb9ab4-e5fc-4eb3-9dfb-f95ea14871da)

1. Save a search.
2. Try to export with Excel from said search.

**Comment by NiklasBr** [comment]
It appears that `$request->get('field')` in `DataObjectHelperController::doExportAction()` now contains an array like this:

```php
[
  0 = "ArticleId",
  1 = "#62ffa09829873",
  2 = "SystemArticleName",
  3 = "MainMaterialCompositions",
  4 = "MainGroup",
  5 = "ArtGroup",
  6 = "Subgroup",
  7 = "#62ffa09829875",
  8 = "#62ffa09829876",
  9 = "#62ffa09829877",
  10 = "#62ffa09829878",
  11 = "#62ffa09829879",
  12 = "#62ffa0982987a",
]
```

But it should be something like according to `Service.php`:
```php
[
  0 = ['key' => something, 'label' => something else ],
  1 = ['key' => something, 'label' => something else ],
  2 = ['key' => something, 'label' => something else ],
  3 = ['key' => something, 'label' => something else ],
  4 = ['key' => something, 'label' => something else ],
  and so on…
]
```

**Comment by NiklasBr** [comment]
I don't know if this is a case of missing migration due to changed configuration data structure in Pimcore 11 vs 10 or something else.

**Comment by jtwogw** [comment]
@NiklasBr  we also encountered the same issue. 
https://github.com/orgs/pimcore/discussions/16706
Any possible fix?

**Comment by NiklasBr** [comment]
@jtwogw unfortunately I have not been able to find any solution.

**Comment by NiklasBr** [comment]
@jtwogw I think this patch for `pimcore/admin-ui-classic-bundle`'s file `pimcore/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectHelperController.php` could work, can you try it on your end and see if you have any success?



```patch
Index: src/Controller/Admin/DataObject/DataObjectHelperController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Controller/Admin/DataObject/DataObjectHelperController.php b/src/Controller/Admin/DataObject/DataObjectHelperController.php
--- a/src/Controller/Admin/DataObject/DataObjectHelperController.php
+++ b/src/Controller/Admin/DataObject/DataObjectHelperController.php	(date 1709637349450)
@@ -1340,7 +1340,13 @@
 
         $list = $beforeListExportEvent->getArgument('list');
 
-        $fields = json_decode($request->get('fields')[0], true);
+        $fields = [];
+        foreach ($request->get('fields') as $field) {
+            $fields[] = [
+                'key' => $field,
+                'label' => $field,
+            ];
+        }
 
         $addTitles = (bool) $request->get('initial');

```

I have no idea if it has any side effects or if there is a better way to fix it, but now we can at least export from Advanced Object Search again.

**Comment by jtwogw** [comment]
@NiklasBr  it has a side effect, 
After this code, Data object => folder, export has empty rows. 

"[{"key":"id","label":"id"},{"key":"fullpath","label":"fullpath"},{"key":"published","label":"published"},{"key":"name","label":"Name"}]"
""
""
""
""
""
""
""
""

**Comment by NiklasBr** [comment]
That's a good catch @jtwogw, try this adjusted patch which should work on both regular grid view and Advanced Object Search:

```patch
Index: src/Controller/Admin/DataObject/DataObjectHelperController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Controller/Admin/DataObject/DataObjectHelperController.php b/src/Controller/Admin/DataObject/DataObjectHelperController.php
--- a/src/Controller/Admin/DataObject/DataObjectHelperController.php
+++ b/src/Controller/Admin/DataObject/DataObjectHelperController.php	(date 1709637349450)
@@ -1340,7 +1340,17 @@

         $list = $beforeListExportEvent->getArgument('list');

-        $fields = json_decode($request->get('fields')[0], true);
+        if (json_validate($request->get('fields')[0])) {
+            $fields = json_decode($request->get('fields')[0], true);
+        } else {
+            $fields = [];
+            foreach ($request->get('fields') as $field) {
+                $fields[] = [
+                    'key' => $field,
+                    'label' => $field,
+                ];
+            }
+        }

         $addTitles = (bool) $request->get('initial');

```

**Comment by jtwogw** [comment]
@NiklasBr  
I had reverted the changes on DataObjectHelperController and kept the original code from the pimcore. 

Made this temporary fix, this change the request parameter from Advanced-Object-Search module instead of changing on Pimcore DataObjectHelperController.
https://github.com/jtwogw/advanced-object-search/commit/2ed21e800ca21bd6159d811c2850c9543062f0ae

From here: 
src/Resources/public/js/searchConfig/resultPanel.js

Not sure if this is a good place to fix the issue, anyway this works for both cases in my case. 

--- For Prod ENV -- 
cache:clear and pimcore:cache:clear did not worked for prod ENV. 
had to delete /public/bundles/ 
Run Composer install to regenerate /public/bundles/
