### ISSUE TITLE
Custom mapping

### ISSUE THREAD

**Issue by ngeleedst** [pimcore/advanced-object-search#30]
Hi,

I would like to know of custom object mapping is possible? I like to use the same schema that is being used by VUE JS storefront.

**Comment by fashxp** [comment]
you would have to modify [these configs here](https://github.com/pimcore/advanced-object-search/blob/master/src/Resources/config/pimcore/config.yml#L2) and implement your own `FieldDefinitionAdapters` that define the mapping and how to index/query data.
