### ISSUE TITLE
Feature request: config should follow symfony/pimcore rules for dev/prod

### ISSUE THREAD

**Issue by ITspirit** [pimcore/advanced-object-search#38]
Currently, the advanced-object-search only read the config from "config.php".

Ist should detect and read (if given) the config files in conjunction with the enviroment (dev/prod).
This is usefull, to define different elasticsearch instances for dev and prod for example.

config_dev.php
config_prod.php
config.php

**Comment by fashxp** [comment]
or even better: switch to symfony config tree :)

**Comment by fashxp** [comment]
but that would be a BC-break

**Comment by NiklasBr** [comment]
@fashxp I like the PR here and would love to see it merged

**Comment by fashxp** [comment]
hmm, there is no PR (yet?)

**Comment by NiklasBr** [comment]
Sorry, clicked the commit above and failed to see that it was not a request.
