### ISSUE TITLE
Feature Request: Block Indexing 

### ISSUE THREAD

**Issue by tazdij** [pimcore/advanced-object-search#4]
Hey there, thank you for the amazing plugin. I am planning on using it on a current project :)
I would like to be able to search for objects based on data contained in Block. for my specific use case; I have Blocks which contain a handful of fields, with information and certifications, and product SKU numbers. There are usually 10 of these blocks or so, on each object. I am certain that customers will come to the site searching for their specific SKU instead of the more generic product number.

Example data structure:
_in this structure the skus are blocks containing text input fields._
`
{
    "productNumber": "T1X50",
    "skus": [
      {
        "sku": "T1X50-US",
        "countries": "US,CA,MX",
        "MSRP": "1526.00",
        "channel": "Rinco"
      },
      {
        "sku": "T1X50-BR",
        "countries": "BR",
        "MSRP": "1226.00",
        "channel": "PaoCa"
      }]
}
`

Is it reasonable to ask for this feature? And if not, what can I do to help out getting this feature implemented?

**Comment by fashxp** [comment]
Hey, this feature is definitely reasonable. Could you provide a pull request? I could be implemented similar to localized fields.

**Comment by tazdij** [comment]
The code for this project is hosted on a local repository, So I am not sure how to go about making the pull request. How should I proceed?

**Comment by mbolka** [comment]
@tazdij Create fork to your local repository and then on your local machine:
```
git clone git@github.com:[YOUR REPOSITORY]/advanced-object-search.git && cd advanced-object-search
$ git remote add pimcore git@github.com/pimcore/advanced-object-search.git # add second remote repository
$ git pull pimcore master # merge Plugin changes into you repo (from pimcore's remote)
$ git push origin master # update your repository
$ git checkout -b feature/block-support # create a branch allowing other developers to review your changes
$ vi file.php # do some changes
$ git add .  commit -m "Adding new functionality" # commit changes
$ git push origin feature/block-support  # push changes into your repository
```
Then in your browser navigate to your fork and you will see on top of the page: "Your recently pushed branches:" and below that button: Compare & Pull request <- click on it

**Comment by fashxp** [comment]
close this for now due to inactivity. PRs are still welcome.
