### ISSUE TITLE
Error  on add columns in Grid Options

### ISSUE THREAD

**Issue by vmalyk** [pimcore/advanced-object-search#43]
After open "Grid Options" I got exception http://prntscr.com/mie86c:

`Timestamp: Fri Feb 08 2019 16:56:24 GMT+0300 (Москва, стандартное время)
Status: 500 | Internal Server Error
URL: /admin/object/grid-proxy?classId=undefined&folderId=undefined
Method: POST
Message: Call to a member function getName() on null`

Might it be related with undefined  values for  classId and folderId

**Comment by fashxp** [comment]
see https://github.com/pimcore/pimcore/issues/3945
