### ISSUE TITLE
[Documentation] Should advise to launch index command at first install

### ISSUE THREAD

**Issue by FredoVelcro** [pimcore/advanced-object-search#46]
Hello,

In the installation section, you should specify that we need to launch 
php bin/console advanced-object-search:re-index
at first to create indexes that don't exists yet.
Thanks !

**Comment by fashxp** [comment]
fixed with https://github.com/pimcore/advanced-object-search/commit/18f876b9cd4d1bc2c282d5753700045f221a4110
