### ISSUE TITLE
Get object relation with properties

### ISSUE THREAD

**Issue by turgic** [pimcore/advanced-object-search#51]
Hello guys, I have a relation to supplier from CoreshopProduct. Something like that : 
![Screenshot from 2019-07-12 17-49-44](https://user-images.githubusercontent.com/6445778/61137113-8e0d5480-a4cd-11e9-90bd-34eb67526082.png)

And from supplier I have relation to product : 
![Screenshot from 2019-07-12 17-51-07](https://user-images.githubusercontent.com/6445778/61137154-ada47d00-a4cd-11e9-8be9-ecd61c8c12bf.png)

But when I trying to get products like this : 
```
eturn $this->advancedObjectSearchService->doFilter(14,
                [
                    new FilterEntry(
                        "categories",
                        [
                            "type" => "object",
                            "id" => $category->getId()
                        ],
                        BoolQuery::SHOULD
                    )
                ],
                ""
            );
```
I don't have all properties of supplier like : name, city, etc. I have only the id
![Screenshot from 2019-07-12 17-53-23](https://user-images.githubusercontent.com/6445778/61137315-f65c3600-a4cd-11e9-81d0-5e2d903acb25.png)

Have you an idea about that ?

**Comment by fashxp** [comment]
yes, this is on purpose, because also in index there are only the IDs and not any other properties. 

what is your usecase?

**Comment by turgic** [comment]
@fashxp I want to get in this request and all properties all supliers, not only the id...in order to avoid a new call to the api based on supplier id for getting remaining properties.

**Comment by fashxp** [comment]
advanced object search is not built for that right now. it is just a search index, not meant to get data out of it. 
for your use case maybe https://github.com/pimcore/data-hub might be better?

**Comment by turgic** [comment]
ok, thank you @fashxp
