### ISSUE TITLE
Get only product whitout variants

### ISSUE THREAD

**Issue by turgic** [pimcore/advanced-object-search#52]
Hello, I tried to get only product whitout variants, but I have a error. In my case a product that is not variant has `suppliers`  = `NULL`.
![Screenshot from 2019-07-18 14-26-16](https://user-images.githubusercontent.com/6445778/61453900-0362a480-a968-11e9-8843-e3d10d4dc648.png)

My code : 
```
 return $this->advancedObjectSearchService->doFilter(14,
            [
                new FilterEntry("suppliers", "NULL")
            ],
            "");
```
The error is : 
```
"invalid filter entry for relations filter: NULL"
```

**Comment by fashxp** [comment]
I think you need to work with operator `NOT_EXISTS` ...
so use something like: 
```
new FilterEntry("suppliers", "", FilterEntry::NOT_EXISTS)
```
