### ISSUE TITLE
Empty value existing Saved Search for Numeric field

### ISSUE THREAD

**Issue by vmalyk** [pimcore/advanced-object-search#55]
Hi, I found issue with Numeric fields. When I setup search and view results - it works fine: Ex., 
https://prnt.sc/ouggit. But after save and re-open i- It hasn`t value - it`s empty.  https://prnt.sc/ough2k. As result,User gets error of search: https://prnt.sc/ougimn

**Comment by fashxp** [comment]
fixed by #57
