### ISSUE TITLE
Many to many relation for variants

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/advanced-object-search#63]
In the ManyToOne field definition adapter searches for object_ids are always added for the type 'object'. In some of our projects we also use variants and the type property in Elastic is set to 'variant' instead of 'object' which results in an empty search.

2 possible changes that can be made:

1. Change the index task to set the type always to 'object' (ofcourse for objects...)
2. Add 'variant' search as well in the `getQueryPart`inside `ManyToOneRelation` adapter

**Comment by fashxp** [comment]
is there really a difference between objects and variants in advanced object search? 
I guess not

**Comment by RuudvdvNB** [comment]
Well, i can imagine that it would be easy to have an option to search for objects or variants because sometimes you don't need all the variants and just the main product / object.

**Comment by fashxp** [comment]
That's true, but that would be another issue. 
If I understand your issue correctly, you get an empty search result because variants seem not to be considered?

**Comment by RuudvdvNB** [comment]
Yes that is indeed my issue at this moment.

**Comment by fashxp** [comment]
And I don't see why since I don't think there is a difference between variants and object in advanced object search. 
could you try to debug and dig a bit deeper? 
thanks.

**Comment by RuudvdvNB** [comment]
For a client we add 'certifications' on products, these certifications are objects with multiple variants. In Elastic this relation is saved like this:

```
"certification": {
  "standard": [
    {
      "type": "variant",
      "id": 7349
    }
  ],
  "notInherited": [
    {
      "type": "variant",
      "id": 7349
    }
  ]
}
```

When i start a new search i add the folowing condition: 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/36728652/71660844-980d6300-2d4c-11ea-9e0b-f35d690dc023.png">

In the class `\AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToOneRelation` in the method `getQueryPart` a `BoolQuery` is added for the field filter type.

```
$innerBoolQuery = new BoolQuery();
$innerBoolQuery->add(new TermQuery($path . ".type", $fieldFilter['type']));
$innerBoolQuery->add(new TermQuery($path . ".id", $id));
```

The field filter type in this case is `object` resulting in an empty result. I have added a second BoolQuery and hardcoded it to `variant` instead of the field filter type to test which gives me the expected result.

**Comment by fashxp** [comment]
now I get you. 
To fix this, a reindex is necessary.
