### ISSUE TITLE
Search results grid is broken on Pimcore 6.3.0

### ISSUE THREAD

**Issue by vmalyk** [pimcore/advanced-object-search#64]
If open "Results" tab you got empty panel and error in console. https://prnt.sc/pzzig6Issue is related with removed method buildColumnConfigMenu from parent class. It's result fo PR in Pimcore repository [#5093](https://github.com/pimcore/pimcore/pull/5093).
These BC changes aren`t present in Pimсore 6.3.0 changelog.

**Comment by vmalyk** [comment]
@fashxp, I think it should be added to 1.x version to (as new 1.13.0)?

**Comment by fashxp** [comment]
see https://github.com/pimcore/pimcore/issues/5304

**Comment by fashxp** [comment]
lets see if we can fix that on pimcore core side.
