### ISSUE TITLE
Add core fields to object mapping

### ISSUE THREAD

**Issue by wujku** [pimcore/advanced-object-search#67]
Is it possible to add some fields to object mapping?
- `o_creationDate`
- `o_modificationDate`
- `o_published`
- `o_type`

**Comment by fashxp** [comment]
sure why not. do you want to provide a PR?

**Comment by wujku** [comment]
@fashxp I successfully added these fields to mapping.
I wonder about filtering support but core fields has not in fieldDefinitions. 
Would you have an idea how this could be approached?

**Comment by fashxp** [comment]
use default adapter for filtering? 
https://github.com/pimcore/advanced-object-search/blob/master/src/Filter/FieldDefinitionAdapter/DefaultAdapter.php

**Comment by wujku** [comment]
Best place for this modification is that method:
https://github.com/pimcore/advanced-object-search/blob/6f1163fadda8e289941c86a79cab14fdfd052751/src/Service.php#L113-L124

But core fields has not in `$definition->getFieldDefinitions()`. 

I could add custom logic below foreach statement and use new method similar to `getFieldDefinitionAdapter` (I should add similiar method for fields without FieldDefinition).

https://github.com/pimcore/advanced-object-search/blob/6f1163fadda8e289941c86a79cab14fdfd052751/src/Service.php#L91

**Comment by fashxp** [comment]
fixed with #69
