### ISSUE TITLE
ElasticSearch 7.x support

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/advanced-object-search#75]
Hello,

Is there a planned version of this plugin supporting ElasticSearch 7.x ?
I have this error with the mapping creation console command : 
```json
  {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping r
  equests, unless the include_type_name parameter is set to true."},"status":400}
```
Best regards,
Fred

**Comment by fashxp** [comment]
Hi, planned yes, ETA not yet. PRs are welcome ;-) . 
Question would be, if it is possible to support both, ES 6 and ES 7.

**Comment by vburghelea** [comment]
Hi, Christian - is there anything we could do to bump prioritization for having an ES7-enabled version of this component? From what I could tell, the biggest issue would be switching ongr/elasticsearch-dsl to version 7, which adds the necessary support.

**Comment by fashxp** [comment]
hi, you could start off with a PR. 
As I wrote above, it would be great if we can support both, ES6 and ES7. Not sure if this is possible though.

**Comment by jdreesen** [comment]
I think it should be possible to support both versions. 
The biggest change is that there are no more index types in v7 - but as Advanced Object Search already uses an index per object the transition should be easy (just change the type to `_doc`).

**Comment by prazian** [comment]
Regarding @jdreesen this should be the only place we should change to `_doc` I think:

https://github.com/pimcore/advanced-object-search/blob/f83ab724408808767bea4c9fdd07bfaa4452cd94/src/Service.php#L247

As we have one type per index we should be good with that, but I'm not sure if we should re-index with the new doc type (the value of `_type` should become `_doc`) before migrating to 7.x or it will be done automatically. 🤷‍♂️
