### ISSUE TITLE
 Is not a function in resultpanel.js.

### ISSUE THREAD

**Issue by parajuliminiyan** [pimcore/advanced-object-search#76]
- I am getting Error while generating results on console as 
 `this.buildColumnConfigMenu();` is not a function.
 In resultPanel.js at line no `238`;

Any Solutions??

**Comment by fashxp** [comment]
how can we reproduce that?

**Comment by parajuliminiyan** [comment]
![image](https://user-images.githubusercontent.com/19756801/72968885-828bd600-3dec-11ea-8743-25dfd36f322c.png)


![image](https://user-images.githubusercontent.com/19756801/72968904-8c153e00-3dec-11ea-8c6c-2bef26a3f0fd.png)

**Comment by fashxp** [comment]
hmm, works for me on demo.pimcore.fun ... on which versions are you (pimcore & advanced object search)?

**Comment by parajuliminiyan** [comment]
I am on pimcore 6.3.6 and advanced object search version 2.2.0..

**Comment by fashxp** [comment]
ok 2.2.0 was a broken release (already deleted). please try updating to 3.0.0 ... (reinstall of the bundle might be needed after update)

**Comment by parajuliminiyan** [comment]
okay thank you so much.
