### ISSUE TITLE
Selected Grid Rows not Exported on CSV

### ISSUE THREAD

**Issue by parajuliminiyan** [pimcore/advanced-object-search#78]
![image](https://user-images.githubusercontent.com/19756801/73169199-b2f0ae80-4123-11ea-98ca-d49fb2dcc36b.png)
![image](https://user-images.githubusercontent.com/19756801/73169216-bb48e980-4123-11ea-91e9-d3bb4e2968eb.png)
![image](https://user-images.githubusercontent.com/19756801/73169248-c7cd4200-4123-11ea-8ef0-8af1d4e3f398.png)

**Comment by dvesh3** [comment]
should be covered in #73

**Comment by parajuliminiyan** [comment]
I have the latest version of advanced-object-search i.e 3.0.0 but this issue is still there!!!

**Comment by dvesh3** [comment]
@parajuliminiyan this is not yet fixed..should be fixed by mentioned refactoring issue
