### ISSUE TITLE
Advanced object search not working in latest version 6.5.2

### ISSUE THREAD

**Issue by rojalpradhan** [pimcore/advanced-object-search#84]
After installing the latest version of pimcore the advanced object shows 500 internal server error. While it is working in pimcore 6.4.2
![image](https://user-images.githubusercontent.com/54972288/76495987-25151c80-6460-11ea-93f1-2c51bd626cab.png)

**Comment by rojalpradhan** [comment]
downgrading the ongr/elasticsearch-dsl to 6.0.3 solved the issue

**Comment by dvesh3** [comment]
@rojalpradhan there is Incompatibility issue in Elasticsearch DSL 6.1.1 and 7.1.1 https://github.com/ongr-io/ElasticsearchDSL/issues/309. please check and fix your dependencies
