### ISSUE TITLE
Deprecation warning: accessing private service from container in Symfony 3.4.*

### ISSUE THREAD

**Issue by macghriogair** [pimcore/advanced-object-search#9]
Pimcore version: "pimcore/core-version": "v5.1.2"
Symfony version: "symfony/symfony": "3.4.*"

Hi, when running the re-index command I see the following deprecation warning:

> User Deprecated: The "bundle.advanced_object_search.filter.default" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

This is due to services being private by default since Symfony 3.4 (see https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default) and it is recommended to either make it public (possible code smell) or inject it.

The affected lines are for instance in AdvancedObjectSearchBundle\Service line 86ff.

```
public function getFieldDefinitionAdapter(ClassDefinition\Data $fieldDefinition, bool $considerInheritance) {
        $adapter = null;

        try {
            $adapter = $this->container->get("bundle.advanced_object_search.filter." . $fieldDefinition->fieldtype);
        } catch (\Exception $exception) {
            $adapter = $this->container->get("bundle.advanced_object_search.filter.default");
        }

        $adapter->setConsiderInheritance($considerInheritance);
        $adapter->setFieldDefinition($fieldDefinition);

        return $adapter;
    }
```

Probably not desired to inject all Filters here, so maybe make the services public?

**Comment by fashxp** [comment]
or we make a filter locator ... we'll have a look at it...

**Comment by macghriogair** [comment]
since this might seem just a minor & following your suggestion see PR https://github.com/pimcore/advanced-object-search/pull/13
