### ISSUE TITLE
Pimcore 6 support? 

### ISSUE THREAD

**Issue by danmichaelo** [pimcore/advanced-object-search#95]
Hi. Does this plugin work with Pimcore 6?

**Comment by dvesh3** [comment]
yes! https://github.com/pimcore/advanced-object-search/blob/master/composer.json#L10

For queries always use our official forum https://talk.pimcore.org/ Thanks!

**Comment by danmichaelo** [comment]
Thanks! And sorry for not including it initially, but the reason I asked was because of the information at https://pimcore.com/en/developers/marketplace/pimcore/advanced-object-search_e5482 . You might want to update that page in that case

**Comment by fashxp** [comment]
thx, updated information there.
